### ISSUE TITLE
Notes not loading after a meeting is completed

### ISSUE THREAD

**Issue by kartikeypro** [rajat2502/StandNote#10]
I used Standnote for a meeting but when I finished it, my notes weren't loading when I click on one of them. They were saved in the Dashboard but on clicking on one of them the page just keeps loading without my application showing.

**Comment by rajat2502** [comment]
Hey @kartikeypro, thanks for reporting it!
Can you please mention the time you took the meeting so that we can see the logs?

**Comment by kartikeypro** [comment]
The email ID is rsharmasingh2@gmail.com. I made a note around 5 PM yesterday.

**Comment by kartikeypro** [comment]
The email ID is rsharmasingh2@gmail.com. I made a note around 5 PM yesterday.

**Comment by PragatiVerma18** [comment]
Hey @kartikeypro, I checked for you, the notes are being generated successfully after each meeting. Please try again and in case, you face any other problems, do let us know.

**Comment by kartikeypro** [comment]
Hi, It's not that notes aren't being generated. I can see them being generated. It's just that they aren't loading. As soon as I click on it, the app just keeps loading without them opening. Maybe you could open it from another account or incognito mode and see if the user notes are loading or not. I can share a video if that helps.

**Comment by rajat2502** [comment]
Hey @kartikeypro, I checked it out in incognito mode and the notes were loading correctly, maybe you should share a video so that we can see the exact issue!

**Comment by kartikeypro** [comment]
https://drive.google.com/file/d/1MNNDgdqdTPwd8OpvwwBHwBgU3fBSsXwq/view?usp=sharing
Here is a video of the notes not loading. I asked a friend to test it as well and the same was happening there.
