### ISSUE TITLE
Backend Setup Steps not clear

### ISSUE THREAD

**Issue by rishabhCoder1** [rajat2502/StandNote#11]
This is a really cool project. I am trying to set up the backend but the social application login steps are not clear to me. There are three windows that I can see here. Could you please guide me regarding the steps to set up the social logins. My login system is not working because of this issue. Attaching images of the three windows that I can see in the set up.
 
![WhatsApp Image 2021-02-13 at 1 07 28 PM](https://user-images.githubusercontent.com/78980853/107845895-191aa300-6e05-11eb-8d83-283613d793e6.jpeg)
![WhatsApp Image 2021-02-13 at 1 07 27 PM](https://user-images.githubusercontent.com/78980853/107845896-19b33980-6e05-11eb-8890-dcbb8bd608f8.jpeg)
![WhatsApp Image 2021-02-13 at 1 07 27 PM (1)](https://user-images.githubusercontent.com/78980853/107845897-1ae46680-6e05-11eb-8b96-bfcb42e9ac28.jpeg)

 Waiting for a response.

**Comment by PragatiVerma18** [comment]
Hey @rishabhCoder1, thanks for checking out StandNote. Regarding your issue, these are steps you can follow along to setup the login functionality:
1. Go to `Home › Social Accounts › Social applications` in the Django Admin Panel, and add a social application as per the following specifications:
    - **Provider:** Google
    - **Name:** Google API
    - **Client id**: Client ID from [Google Developer Console](https://console.developers.google.com/apis/credentials)
    - **Secret Key:** Secret Key that you get after adding an app on [Google Developer Console](https://console.developers.google.com/apis/credentials)
 2. Go to `Home › Sites › Sites`, Add `http://localhost:3000` and `http://127.0.0.1:8000` in the sites
 3. Go back to `Home › Social Accounts › Social applications › Google API`, Choose `http://localhost:3000` and `http://127.0.0.1:8000`, save and it's done!

I hope this helps you. In case you have any doubts, please let us know through comments.
