### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [rajat2502/StandNote#14]
Your README currently looks great! I would recommend adding:

* How users can setup the project on their local machine for contributions.
* Explaining to users you have a LEARN.md file
* Mention your CONTRIBUTING file
* Mention your code of conduct

**Comment by PragatiVerma18** [comment]
Hey @ericdrosado, our README already has the setup steps for both frontend and backend inside a collapsible. If you say, I can remove it from the collapsible and add it as normal text.

![image](https://user-images.githubusercontent.com/42115530/170109122-f3bf4c63-78e4-4743-b593-ffd1650e12fa.png)

**Comment by ericdrosado** [comment]
@PragatiVerma18 you can keep it collapsible. The header should allow folks the ability to find it.
