### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by ericdrosado** [rajat2502/StandNote#15]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Currently it is long. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

**Comment by PragatiVerma18** [comment]
@ericdrosado Will this work? - 

StandNote is a chrome extension that generates automated meeting minutes after every online meeting and helps save time for students and professionals.

**Comment by ericdrosado** [comment]
@PragatiVerma18 - that is a perfect repo description! Feel free to update and close this issue once you have done so. 🚀

**Comment by PragatiVerma18** [comment]
Done @ericdrosado 🚀
