### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by ericdrosado** [rajat2502/StandNote#16]
As the maintainer of a `Collaborate` repo, keeping Issues up-to-date will help the student community understand what they can do to contribute. Issues should vary by the easy (update documentation) to the difficult (add a new feature). The more involved you are, the more opportunities there are to collaborate.

Recommendations:
* Add issues of varying difficulty to the repo often.
* Generate issues even if you plan on solving them, so the repository appears as active.
* Contribute/commit often to the repo so it does not go stale.

In order to submit your project into CX you will need at least one issue, but we recommend more so other students have an idea on where to start.

**Comment by PragatiVerma18** [comment]
@ericdrosado I have added a few issues, for now, will keep adding more. Hope this works for now. Please let me know if we can close this issue.

**Comment by ericdrosado** [comment]
Looks great @PragatiVerma18 ! Thank you for adding those issues. 🚀
